# Generated by Django 5.1 on 2024-08-23 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=255)),
                ("event_description", models.TextField()),
                ("event_date", models.DateField()),
                ("event_location", models.CharField(max_length=255)),
                ("event_image", models.FileField(upload_to="")),
                ("target_population", models.CharField(max_length=255)),
                ("skillset", models.TextField()),
                ("participant_quota", models.IntegerField()),
                ("volunteer_quota", models.IntegerField()),
                ("deadline", models.DateTimeField()),
                (
                    "registered_participants",
                    models.ManyToManyField(
                        related_name="registered_participants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registered_volunteers",
                    models.ManyToManyField(
                        related_name="registered_volunteers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
