# Generated by Django 5.1 on 2024-08-23 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_image",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="event",
            name="registered_participants",
            field=models.ManyToManyField(
                null=True,
                related_name="registered_participants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="registered_volunteers",
            field=models.ManyToManyField(
                null=True,
                related_name="registered_volunteers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="skillset",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="target_population",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
