# Generated by Django 5.1 on 2024-08-23 09:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_event_event_image_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="registered_participants",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="registered_participants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="registered_volunteers",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="registered_volunteers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
