# Generated by Django 5.1 on 2024-08-23 11:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_training"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-event_name"]},
        ),
    ]
