# Generated by Django 5.1 on 2024-08-23 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_event_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={},
        ),
    ]
