# Generated by Django 4.2.15 on 2024-08-23 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0006_alter_event_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=225)),
                ("age", models.PositiveIntegerField()),
                (
                    "gender",
                    models.TextField(choices=[("MALE", "male"), ("FEMALE", "female")]),
                ),
                (
                    "role_type",
                    models.TextField(
                        choices=[
                            ("STAFF", "staff"),
                            ("VOLUNTEER", "volunteer"),
                            ("PARTICIPANT", "participant"),
                        ]
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role_type",
                    models.TextField(
                        choices=[
                            ("STAFF", "staff"),
                            ("VOLUNTEER", "volunteer"),
                            ("PARTICIPANT", "participant"),
                        ]
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="api.event",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="api.profile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="staff",
            field=models.ManyToManyField(
                limit_choices_to={"role_type": "staff"},
                related_name="managed_events",
                through="api.Application",
                to="api.profile",
            ),
        ),
    ]
