# Generated by Django 5.1 on 2024-08-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_badge_profile_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='required_training',
            field=models.ManyToManyField(blank=True, related_name='required_training', to='api.training'),
        ),
        migrations.AddField(
            model_name='profile',
            name='trainings',
            field=models.ManyToManyField(blank=True, related_name='completed_trainings', to='api.training'),
        ),
    ]
