# Generated by Django 4.2.15 on 2024-08-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_event_required_training_profile_trainings'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='pre_requisites',
            field=models.TextField(blank=True, null=True),
        ),
    ]
