# Generated by Django 4.2.15 on 2024-08-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_badge_pre_requisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
