# Generated by Django 4.2.15 on 2024-08-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_profilebadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ethnicity',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nationality',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
