# Generated by Django 4.2.15 on 2024-08-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_profile_ethnicity_profile_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ethnicity',
            field=models.CharField(default='Unknown', max_length=225),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='nationality',
            field=models.CharField(default='Unknown', max_length=225),
            preserve_default=False,
        ),
    ]
