# Generated by Django 4.2.15 on 2024-08-24 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_volunteerapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='role_type',
        ),
        migrations.AddField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 8, 24, 16, 58, 36, 537429, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
