# Generated by Django 5.1 on 2024-08-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_application_role_type_profile_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('receiver_group', models.TextField(blank=True, choices=[('STAFF', 'staff'), ('VOLUNTEER', 'volunteer'), ('PARTICIPANT', 'participant')], null=True)),
                ('recipient_list', models.TextField()),
            ],
        ),
    ]
