# Generated by Django 4.2.15 on 2024-08-25 08:55

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_emailtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.CharField(default=api.models.generate_random_id, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
