# Generated by Django 4.2.15 on 2024-08-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.FileField(blank=True, null=True, upload_to='static/event_image/'),
        ),
    ]
