# Generated by Django 5.1 on 2024-08-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0021_alter_event_event_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsappTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                (
                    "receiver_group",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("STAFF", "staff"),
                            ("VOLUNTEER", "volunteer"),
                            ("PARTICIPANT", "participant"),
                        ],
                        null=True,
                    ),
                ),
                ("recipient_list", models.TextField()),
            ],
        ),
    ]
