# Generated by Django 4.2.15 on 2024-08-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_add_status_to_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='role_type',
            field=models.TextField(choices=[('STAFF', 'staff'), ('VOLUNTEER', 'volunteer'), ('PARTICIPANT', 'participant')], default='volunteer'),
            preserve_default=False,
        ),
    ]
